### ISSUE TITLE
Getting error while Webpack compilation.

### ISSUE THREAD

**Issue by ashishdhyani** [erfangc/GigaGrid#89]
Hi @caguthrie , 
I am trying to use in React application. 
I am getting below error.

ERROR in ./~/giga-grid/styles/theme/Retro.styl
Module parse failed: C:\Project\node_modules\giga-grid\styles\theme\Retro.styl Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp$4.raise (C:\Project\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (C:\Project\node_modules\webpack\node_modules\acorn\dist\acorn.js:2756:10)
    at Parser.pp$7.readToken (C:\Project\node_modules\webpack\node_modules\acorn\dist\acorn.js:2477:17)
    at Parser.pp$7.nextToken (C:\Project\node_modules\webpack\node_modules\acorn\dist\acorn.js:2468:15)
    at Parser.parse (C:\Project\node_modules\webpack\node_modules\acorn\dist\acorn.js:515:10)
    at Object.parse (C:\Project\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Project\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\Project\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\Project\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\Project\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
 @ ./dev/js/containers/pivot-table.js 17:0-44
webpack: Failed to compile.

**Comment by erfangc** [comment]
do you have a stylus loader?
https://www.npmjs.com/package/stylus-loader

**Comment by ashishdhyani** [comment]
Thanks erfangc.
I have installed stylus-loaded with below webpack config

`{
    test: /\.styl$/,
    loader: 'style-loader!css-loader!stylus-loader'
 }`


now I am getting this error 

ERROR in Cannot find module 'stylus'
 @ ./~/giga-grid/styles/theme/Retro.styl 4:14-104

**Comment by ashishdhyani** [comment]
thanks erfangc.
It works. Default.Styl working well.

But somehow Retro.styl doesnt seems to work properly.
